config/routes.rb
Rails.application.routes.draw do
  root 'theatres#welcome'
  get 'sessions/new'
  get '/signup',to: 'customers#new'
  post '/signup',to: 'customers#create'
  get '/login',to: 'sessions#index'
  post'/login',to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  resources :customers	
  get "/theatres/list",to:"theatres#list_all_theatre"
  resources :theatres do
  	resources :screens do
      resources :movies 
        

    
    end
  end
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
	 belongs_to :theatre,optional:true
	 validates :name, presence: { message: " please! given movie name"}
	 validates :password,presence: true,length: { minimum: 3 }
	 validates :email, presence: true

	 
end	 

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :theatre
	validates :EmpCode, numericality: true
	validates :name,:address, uniqueness: true,presence: { strict: true,message: "can't leave blank please!"}
end

app/models/movie.rb
class Movie < ApplicationRecord
	belongs_to :screen

	validates :name,uniqueness: true
end

app/models/screen.rb
class Screen < ApplicationRecord
	belongs_to :theatre
	has_one :movie
	has_many :customers, through: :movies
	validates :name,uniqueness: true, presence: { strict: true,message: "can't leave blank please!"}
end

app/models/theatre.rb
class Theatre < ApplicationRecord
	has_many :screens
	has_many :employees
	has_many :customers
	validates :name,uniqueness: true, presence: { strict: true,message: "can't leave blank please!"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	 # before_action :logged_in_customer, only: [:edit, :update]
  def new
		# binding.pry
		  @customer=Customer.new
  end
  def index
     @customer=Customer.all
  end

  def show
        @customer = Customer.find(params[:id])
        #@movie=Movie.find(params[:id])#@theatre=Theatre.find(params[:id])#@screen=Screen.find(params[:id])
  end
  def create
       @customer = Customer.new(customer_params)
     # binding.pry
       if @customer.save
       	session[:customer_id]=@customer.id
       	redirect_to theatres_list_path  #customer new page
	      else
          render :new
        end
  end 
  def edit
     @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
     if @customer.update(customer_params)
       redirect_to @customer  # customer show page
     else
       render :edit
     end
  end

  # def destroy
  #   binding.pry
  # @customer=Customer.find(params[:id])
  # @customer.destroy
  # flash[:success] = "Customer deleted"
  # redirect_to customers_path
  # end
  private
    def customer_params
     params.require(:customer).permit(:name, :email, :password)
    end
   
  # def logged_in_customer
  #      #unless logged_in_customer
  #      flash[:danger] = "Please log in."
  #      redirect_to login_path
  # end
end

  

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	
     def index
     @theatre=Theatre.find(params[:theatre_id])
     @screen=Screen.find(params[:screen_id])
     @movie = Movie.all
     end

     def show
     # binding.pry
     @theatre=Theatre.find(params[:theatre_id])
     @screen=Screen.find(params[:screen_id])
     @movie=Movie.find(params[:id])
     end
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController

    def index
    	@theatre=Theatre.find(params[:theatre_id])
    	
    end

	def show
		# binding.pry
	 @theatre=Theatre.find(params[:theatre_id])
     # @screen=Screen.find(params[:id])
    
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
		# binding.pry
        @customer=Customer.new
   end
   
   def create
  	#binding.pry
  	if customer = Customer.find_by(email: params[:session][:email].downcase,password:params[:session][:password])
        log_in (customer)
        redirect_to theatres_path,notice:"logged in successfully"
    else
        flash[:danger] = 'Invalid email/password combination' # Not quite right!
        render 'new'
    end
   end

   def destroy
		session.delete(:customer_id)
		@current_customer = nil
		redirect_to root_path, notice:"logged out"
	end
end

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
	#http_basic_authenticate_with name: "raghav", password: "R@ghav25", except: [:index, :show]

	def index
		@theatres = Theatre.all
	end

	def show
		# binding.pry
        @theatre=Theatre.find(params[:id])
        # @customer =Customer.find(params[:id])
   	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# binding.pry
	def log_in(customer)
    
      session[:customer_id] = customer.id
    end

    def current_customer
       if session[:customer_id]
         @current_customer=@current_customer || Customer.find_by(id: session[:customer_id])
       end
    end

    
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/customers/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<%= form_with(model: @customer, local: true) do |form| %>
	<div>
	<%= form.label :name %><br>
	<%= form.text_field :name %>
	</div>
	<div>
	<%= form.label :email %><br>
	<%= form.email_field :email %>
	</div>
	<div>
	<%= form.label :password %><br>
	<%= form.password_field :password %>
	</div>
	<div><br>
	<%= form.submit "Save changes", class: "btn btn-primary" %>
	</div>
<% end %>

app/views/customers/index.html.erb
<h1>All customers</h1>
<ol>
<%  @customer.each do |customer| %>
<li>
<%= customer.name %> 
<%= link_to "  Update ",edit_customer_path(customer)%>

</li>
<% end %>
</ol>

<%# if current_customer.admin? && !current_customer?(customers) %>
<%#= link_to "delete",customer_path(@customer),method: :delete,data: { confirm: "You sure?" } %>

app/views/customers/new.html.erb
<h2> Account created successfully</h2>
<h2> ticket booking </h2>
<%= link_to "login",login_path %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "sample app", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<% if logged_in? %>
					    <li><%#= link_to "Users", '#' %></li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							     Account <b class="caret"></b>
							    </a>
						    
								<ul class="dropdown-menu">
								  <li><%= link_to "Profile", current_cusomer %></li>
								  <li><%#= link_to "Settings", '#' %></li>
								  <li class="divider"></li>
								  <li><%= link_to "Log out", logout_path, method: :delete %></li>
							  </ul>
							</li>
					  <% else %>
						<li><%= link_to "Log in", login_path %></li>
					<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cinema</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<h3> movie in audi</h3>
<li>	
<%#=  @screen.movie.name	%>
<%= link_to @screen.movie.name ,theatre_screen_movie_path(theatre_id: @theatre.id, id: @screen.movie.id,screen_id: @screen.id) %>
</li>

app/views/movies/show.html.erb
<h1>booking successful</h1>

<li>Customer Name => <%= current_customer.name %> </li>
<li>Customer Email => <%= current_customer.email %></li>

<li>Theatre Name => <%= @theatre.name %></li>
<li>Screan  Name => <%= @screen.name%></li>
<li>Movie  Name  => <%= @screen.movie.name %></li>
<br>
<%= link_to "All Customer",  customers_path %>
<br><br>
<%= link_to "Log out", logout_path, method: :delete %>

<%#= link_to "Log out",  theatres_path %>

app/views/screens/index.html.erb
<h2> SELECT AUDI</h2>
<ul>
	  <% @theatre.screens.each do |screen| %> <li>
      	<%= link_to screen.name,  theatre_screen_movies_path( screen_id: @theatre.screens.ids)%>  </li>
      <% end %>
</ul>

app/views/screens/show.html.erb
<h3> movie in audi</h3>
<li>	
<%#=  @screen.movie.name	%>
<%= link_to @screen.movie.name ,theatre_screen_movie_path(theatre_id: @theatre.id, movie_id: @screen.movie.id,screen_id: @screen.id) %>
</li>
<%#= link_to "sign up",new_customer_path %>

app/views/theatres/index.html.erb
<h3>LIST OF ALL THEATRE</h3>
<ul>

	<% @theatres.each do|theatre| %> <li>
	<%= link_to theatre.name,theatre_screens_path(theatre.id)%>  </li>
	<% end %> 
</ul>

app/views/theatres/show.html.erb
<h2> SELECT AUDI</h2>
<ul>
	  <% @theatre.screens.each do |screen| %> <li>
      	<%= link_to screen.name, theatre_screen_path(id: screen.id,theatre_id: @theatre.id)%>  </li>
      <% end %>
</ul>

app/views/theatres/welcome.html.erb
<h2><center>Welcome to BookMyShow</center><h2>
	 <hr width="30%" 
        size="5" 
        color="blue"> <br>
	<ul> 
		<%# @theatre.each do |theatre| %>
      <p align="center"><%= link_to  "add new customer " ,sessions_new_path %>  </p> 
	  <p align="center"><%= link_to  "log in" ,login_path %> </p>
	    
			<%#= link_to "Select Theatre",theatres_list_path %>
		<%# end %>
	</ul>
	